name: Update THSR Calendar

on:
  schedule:
    - cron: '0 0 * * 1'  # 每週一執行
  workflow_dispatch:  # 允許手動觸發

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run update script
      env:
        GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
      run: python main.py